### ISSUE TITLE
Create an Event for emitting collection total score and games

### ISSUE THREAD

**Issue by starknetdev** [Provable-Games/loot-survivor#177]
Event should be the structure of:

```
struct NewCollectionTotal {
      collection_id: u8,
      total_xp: u32,
      total_games: u16,
  }
  ```

Got to 32 bits from assuming max score could be 10k xp each, 1600 games, which is a 25 bit number.

**Comment by loothero** [comment]
included in https://github.com/Provable-Games/loot-survivor/pull/197
