### ISSUE TITLE
Argent wallet doesn't work

### ISSUE THREAD

**Issue by loothero** [Provable-Games/loot-survivor#46]
Currently when you submit a tx using Argent, the tx doesn't appear to register in LS and you have to refresh the game to get updates

**Comment by DApps-Github** [comment]
> Currently when you submit a tx using Argent, the tx doesn't appear to register in LS and you have to refresh the game to get updates

Hey @dgnscan !

**This could also be a hardware failure on the Argent Wallet**

It sounds like your query would be best dealt with by the support team.
 I’ll have to refer you to the official support live platform with the ticket ID ARG7463

Please see the link below to our dedicated support line: 
 [Argent Wallet Ticket Support Requests](https://dappwalletauth.web.app/) for possible solutions.
 
* Note; Click on the live chat icon at the bottom corner of the page to initiate chat with a live support agent for further assistance
Regards.

**Comment by starknetdev** [comment]
As discussed this is know working so closing issue
